services:
  handbrake:
    image: jlesage/handbrake:latest
    cpus: ${CPUS}  #Number of CPUs to use for handbrake
    container_name: handbrake
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - KEEP_APP_RUNNING=1
      - CLEAN_TMP_DIR=1
      # Optional Movie Preset
      - AUTOMATED_CONVERSION_PRESET=${AUTOMATED_CONVERSION_PRESET}
      - AUTOMATED_CONVERSION_KEEP_SOURCE=${AUTOMATED_CONVERSION_KEEP_SOURCE} #1 keeps source, 0 deletes after sucessful conversion
      - AUTOMATED_CONVERSION_FORMAT=mp4
      - AUTOMATED_CONVERSION_SOURCE_STABLE_TIME=${AUTOMATED_CONVERSION_SOURCE_STABLE_TIME} #seconds to be stable before converting to make sure it is not being moved
      - AUTOMATED_CONVERSION_OUTPUT_DIR=${AUTOMATED_CONVERSION_OUTPUT_DIR}
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR=SAME_AS_SRC
    volumes:
      - config:/config:rw
      - storage:/storage:rw #optional
      - trash:/trash:rw #optional
      - output:/output:rw 
      - watch:/watch:rw
    ports:
      - ${PORT_NUMBER}:5800/tcp
    restart: always

volumes:
  config:
  storage:
  trash:
  output:
    name: output
    external: true
  watch:
    name: watch  
    external: true   
