services:
  actual_server:
    image: actualbudget/actual-server:latest
    container_name: Actual
    security_opt:
      - no-new-privileges:true
    ports:
      - ${PORT}:5006
    volumes:
      - data:/data:rw
    restart: always

volumes:
  data: 
