version: '3.3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest 
    container_name: uptime-kuma
    volumes:
      - data:/app/data
    ports:
      - ${PORT}:3001 
    restart: always
volumes:
  data:
