services:
  db:
    image: mysql:9.0
    container_name: ${db_container_name}
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    labels:
      - "com.centurylinklabs.watchtower.enable=false" #Do not update with watchtower
      
  wordpress_whatsnewandrew:
    depends_on:
      - db
    image: wordpress
    ports:
      - ${PORT}:80
    container_name: ${wp_container_name}
    volumes:
      - wpdata:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    labels:
      - "com.centurylinklabs.watchtower.enable=false" #Do not update with watchtower
volumes:
  db:
