services:
  sonarr:
    image: ghcr.io/hotio/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}   
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - ${PORT_NUMBER}:8989/tcp
    restart: always
    volumes:
      - config:/config
      - tvSeries:/tv
      - complete:/complete
      - tvRecycle:/recycle 
volumes:
  config:
  tvSeries:
    name: tvSeries  
    external: true
  complete:
    name: complete  
    external: true
  tvRecycle:
    name: tvRecycle  
    external: true    
