services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    ports:
      - ${PORT}:3000
    environment:
      DATABASE_URL: ${DATABASE_URL} #format postgresql://user:app_secret@db:5432/dbname
      DATABASE_TYPE: postgresql
      APP_SECRET: ${APP_SECRET}
      # optional comma separated list of IPs to ignore for tracking
      IGNORE_IP: ${IGNORE_IP}
    depends_on:
      - db
    restart: always
  db:
    image: postgres:15-alpine
    container_name: Umami-DB
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data:rw
    restart: always

volumes:
  db:
