services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    #security_opt:
    #  - seccomp:unconfined #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - obsidian:/config
    ports:
      - ${PORT_NUMBER1}:3000
      #- ${PORT_NUMBER2}:3001
    #devices:
    #  - /dev/dri:/dev/dri #optional
    shm_size: "1gb"
    restart: always
volumes:
  obsidian:
