services:
  frigate:
    container_name: frigate
    #privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    #cap_add:
    #  - CAP_PERFMON
    shm_size: "128MB" # update for your cameras 
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128 # for intel hwaccel: needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}/config.yml:/config/config.yml:rw # This is where config.yml is stored to hold camera info, etc.
      - media:/media/frigate  # map this folder to either a local or NAS folder.  Ensure you will have enough space
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 8971:8971
      - 5000:5000
      #- ${RTMP_PORT}:1935 # RTMP feeds
      - 8554:8554 # RTSP feeds
      - 8555:8555/tcp # WebRTC over tcp
      - 8555:8555/udp # WebRTC over udp      
    environment:
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_RTSP_PASSWORD}     
volumes:
  media:
    # Next two lines required only if mapping to external location such as NAS NFS location
    name: media
    external: true    
